"""empty message

Revision ID: 068a32cee600
Revises: 67284fcf4c95
Create Date: 2020-04-08 02:33:34.705027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068a32cee600'
down_revision = '67284fcf4c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('search_terms',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.Column('user_query', sa.String(length=128), nullable=True),
    # sa.Column('terms_query', sa.String(length=128), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_terms')
    # ### end Alembic commands ###
