"""empty message

Revision ID: 1162bb443594
Revises: ed5271eaf28a
Create Date: 2020-04-08 05:36:24.513950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1162bb443594'
down_revision = 'ed5271eaf28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('tweet_author', sa.String(), nullable=True),
    sa.Column('tweet_str', sa.String(), nullable=True),
    sa.Column('tweet_time', sa.String(), nullable=True),
    sa.Column('combined_str', sa.String(), nullable=True),
    sa.Column('user_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_checks')
    # ### end Alembic commands ###
