"""empty message

Revision ID: eb1ed41270a7
Revises: fb9b28640204
Create Date: 2020-04-08 04:34:31.406652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1ed41270a7'
down_revision = 'fb9b28640204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_terms', sa.Column('combined_query', sa.String(), nullable=True))
    op.add_column('search_terms', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('search_terms', sa.Column('user_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_terms', 'user_ip')
    op.drop_column('search_terms', 'date_posted')
    op.drop_column('search_terms', 'combined_query')
    # ### end Alembic commands ###
