"""empty message

Revision ID: ed5271eaf28a
Revises: eb1ed41270a7
Create Date: 2020-04-08 04:54:15.854031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

# revision identifiers, used by Alembic.
revision = 'ed5271eaf28a'
down_revision = '67284fcf4c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_ip', sa.String(), nullable=True),
    sa.Column('user_query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_ip', sa.String(), nullable=True),
    sa.Column('user_query', sa.String(), nullable=True),
    sa.Column('terms_query', sa.String(length=128), nullable=True),
    sa.Column('combined_query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_terms', 'date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('search_users')
    # ### end Alembic commands ###
